let &runtimepath='/home/randy/etc/vim/vim/'
set nocompatible
set nu rnu
set hlsearch
set incsearch
set ignorecase smartcase
set undodir=$XDG_DATA_HOME/vim
set directory=$XDG_DATA_HOME/vim
set backupdir=$XDG_DATA_HOME/vim
set viewdir=$XDG_DATA_HOME/vim
set viminfo+=n$XDG_DATA_HOME/vim/viminfo
set runtimepath=~/etc/vim/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after
set noshowmode
set laststatus=2
set t_Co=256

call plug#begin('/home/randy/etc/vim/vim/plugged')
	Plug 'itchyny/lightline.vim'
	Plug 'dylanaraps/wal.vim'
call plug#end()

colorscheme wal
" let g:lightline = {'colorscheme': 'tomorrow'}
" colorscheme wal
let g:lightline = {'colorscheme': 'wombat'}

